openapi: 3.0.0
info:
  title: Node.js HW MongoDB API
  description: API documentation for Node.js HW MongoDB application
  version: 1.0.0
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-tepk.onrender.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    contact:
      $ref: '../swagger/components/schemas/contact.yaml'
  responses:
    Unauthorized:
      $ref: '../swagger/components/responses/401.yaml'
    InternalServerError:
      $ref: '../swagger/components/responses/500.yaml'
security:
  - bearerAuth: []
paths:
  /contacts/{id}:
    get:
      $ref: '../swagger/paths/contacts/{id}/get.yaml'
    patch:
      $ref: '../swagger/paths/contacts/{id}/patch.yaml'
    delete:
      $ref: '../swagger/paths/contacts/{id}/delete.yaml'
  /contacts:
    get:
      $ref: '../swagger/paths/contacts/get.yaml'
    post:
      $ref: '../swagger/paths/contacts/post.yaml'
